"""initial schema

Revision ID: bbfa5454db7e
Revises:
Create Date: 2026-08-23 17:13:02.461224
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "bbfa5454db7e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_hosts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("ip_addresses", sa.JSON(), nullable=False),
        sa.Column("operating_system", sa.String(length=255), nullable=True),
        sa.Column("owner", sa.String(length=255), nullable=True),
        sa.Column("criticality", sa.Float(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_asset_hosts_hostname"), "asset_hosts", ["hostname"], unique=True)
    op.create_table(
        "attack_graph_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_key", sa.String(length=500), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_type", "entity_key", name="uq_graph_node_entity"),
    )
    op.create_index(
        op.f("ix_attack_graph_nodes_entity_type"),
        "attack_graph_nodes",
        ["entity_type"],
        unique=False,
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_username", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_actor_username"), "audit_logs", ["actor_username"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_resource_id"), "audit_logs", ["resource_id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_resource_type"), "audit_logs", ["resource_type"], unique=False
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "investigating",
                "contained",
                "closed",
                name="incident_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "informational",
                "low",
                "medium",
                "high",
                "critical",
                name="incident_severity",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_incidents_severity"), "incidents", ["severity"], unique=False)
    op.create_index(op.f("ix_incidents_status"), "incidents", ["status"], unique=False)
    op.create_table(
        "indicators_of_compromise",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("indicator_type", sa.String(length=50), nullable=False),
        sa.Column("value", sa.String(length=2048), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("indicator_type", "value", name="uq_ioc_type_value"),
    )
    op.create_index(
        op.f("ix_indicators_of_compromise_indicator_type"),
        "indicators_of_compromise",
        ["indicator_type"],
        unique=False,
    )
    op.create_table(
        "model_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("model_type", sa.String(length=100), nullable=False),
        sa.Column("dataset_version", sa.String(length=255), nullable=True),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                name="model_run_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_runs_model_name"), "model_runs", ["model_name"], unique=False)
    op.create_index(op.f("ix_model_runs_status"), "model_runs", ["status"], unique=False)
    op.create_table(
        "raw_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("log_source", sa.String(length=100), nullable=False),
        sa.Column("source_reference", sa.String(length=500), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("checksum"),
    )
    op.create_index(op.f("ix_raw_events_log_source"), "raw_events", ["log_source"], unique=False)
    op.create_index(op.f("ix_raw_events_received_at"), "raw_events", ["received_at"], unique=False)
    op.create_table(
        "user_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=500), nullable=False),
        sa.Column(
            "role",
            sa.Enum("analyst", "administrator", name="user_role", native_enum=False),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_accounts_role"), "user_accounts", ["role"], unique=False)
    op.create_index(op.f("ix_user_accounts_username"), "user_accounts", ["username"], unique=True)
    op.create_table(
        "normalized_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("raw_event_id", sa.Uuid(), nullable=True),
        sa.Column("event_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_ip", sa.String(length=45), nullable=True),
        sa.Column("destination_ip", sa.String(length=45), nullable=True),
        sa.Column("user", sa.String(length=255), nullable=True),
        sa.Column("host", sa.String(length=255), nullable=True),
        sa.Column("protocol", sa.String(length=50), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=True),
        sa.Column(
            "severity",
            sa.Enum(
                "informational",
                "low",
                "medium",
                "high",
                "critical",
                name="event_severity",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("log_source", sa.String(length=100), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["raw_event_id"], ["raw_events.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_normalized_events_destination_ip"),
        "normalized_events",
        ["destination_ip"],
        unique=False,
    )
    op.create_index(
        op.f("ix_normalized_events_event_timestamp"),
        "normalized_events",
        ["event_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_normalized_events_event_type"), "normalized_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_normalized_events_host"), "normalized_events", ["host"], unique=False)
    op.create_index(
        "ix_normalized_events_host_time",
        "normalized_events",
        ["host", "event_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_normalized_events_log_source"), "normalized_events", ["log_source"], unique=False
    )
    op.create_index(
        op.f("ix_normalized_events_raw_event_id"),
        "normalized_events",
        ["raw_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_normalized_events_severity"), "normalized_events", ["severity"], unique=False
    )
    op.create_index(
        op.f("ix_normalized_events_source_ip"), "normalized_events", ["source_ip"], unique=False
    )
    op.create_index(
        "ix_normalized_events_source_time",
        "normalized_events",
        ["source_ip", "event_timestamp"],
        unique=False,
    )
    op.create_index(op.f("ix_normalized_events_user"), "normalized_events", ["user"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("normalized_event_id", sa.Uuid(), nullable=True),
        sa.Column("incident_id", sa.Uuid(), nullable=True),
        sa.Column("model_run_id", sa.Uuid(), nullable=True),
        sa.Column("alert_type", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum(
                "informational",
                "low",
                "medium",
                "high",
                "critical",
                name="alert_severity",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "acknowledged",
                "dismissed",
                "resolved",
                name="alert_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["model_run_id"], ["model_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["normalized_event_id"], ["normalized_events.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False)
    op.create_index(op.f("ix_alerts_incident_id"), "alerts", ["incident_id"], unique=False)
    op.create_index(op.f("ix_alerts_model_run_id"), "alerts", ["model_run_id"], unique=False)
    op.create_index(
        op.f("ix_alerts_normalized_event_id"), "alerts", ["normalized_event_id"], unique=False
    )
    op.create_index(op.f("ix_alerts_severity"), "alerts", ["severity"], unique=False)
    op.create_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    op.create_table(
        "attack_graph_edges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("target_node_id", sa.Uuid(), nullable=False),
        sa.Column("normalized_event_id", sa.Uuid(), nullable=True),
        sa.Column("relationship_type", sa.String(length=100), nullable=False),
        sa.Column("event_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["normalized_event_id"], ["normalized_events.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["source_node_id"], ["attack_graph_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_node_id"], ["attack_graph_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attack_graph_edges_event_timestamp"),
        "attack_graph_edges",
        ["event_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attack_graph_edges_normalized_event_id"),
        "attack_graph_edges",
        ["normalized_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attack_graph_edges_relationship_type"),
        "attack_graph_edges",
        ["relationship_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attack_graph_edges_source_node_id"),
        "attack_graph_edges",
        ["source_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attack_graph_edges_target_node_id"),
        "attack_graph_edges",
        ["target_node_id"],
        unique=False,
    )
    op.create_table(
        "analyst_feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=True),
        sa.Column("incident_id", sa.Uuid(), nullable=True),
        sa.Column("analyst", sa.String(length=255), nullable=False),
        sa.Column("verdict", sa.String(length=50), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["alert_id"], ["alerts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analyst_feedback_alert_id"), "analyst_feedback", ["alert_id"], unique=False
    )
    op.create_index(
        op.f("ix_analyst_feedback_incident_id"), "analyst_feedback", ["incident_id"], unique=False
    )
    op.create_index(
        op.f("ix_analyst_feedback_verdict"), "analyst_feedback", ["verdict"], unique=False
    )
    op.create_table(
        "explanations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("model_run_id", sa.Uuid(), nullable=True),
        sa.Column("method", sa.String(length=100), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("limitations", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["alert_id"], ["alerts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["model_run_id"], ["model_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_explanations_alert_id"), "explanations", ["alert_id"], unique=False)
    op.create_index(
        op.f("ix_explanations_model_run_id"), "explanations", ["model_run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_explanations_model_run_id"), table_name="explanations")
    op.drop_index(op.f("ix_explanations_alert_id"), table_name="explanations")
    op.drop_table("explanations")
    op.drop_index(op.f("ix_analyst_feedback_verdict"), table_name="analyst_feedback")
    op.drop_index(op.f("ix_analyst_feedback_incident_id"), table_name="analyst_feedback")
    op.drop_index(op.f("ix_analyst_feedback_alert_id"), table_name="analyst_feedback")
    op.drop_table("analyst_feedback")
    op.drop_index(op.f("ix_attack_graph_edges_target_node_id"), table_name="attack_graph_edges")
    op.drop_index(op.f("ix_attack_graph_edges_source_node_id"), table_name="attack_graph_edges")
    op.drop_index(op.f("ix_attack_graph_edges_relationship_type"), table_name="attack_graph_edges")
    op.drop_index(
        op.f("ix_attack_graph_edges_normalized_event_id"), table_name="attack_graph_edges"
    )
    op.drop_index(op.f("ix_attack_graph_edges_event_timestamp"), table_name="attack_graph_edges")
    op.drop_table("attack_graph_edges")
    op.drop_index(op.f("ix_alerts_status"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_severity"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_normalized_event_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_model_run_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_incident_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_type"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_normalized_events_user"), table_name="normalized_events")
    op.drop_index("ix_normalized_events_source_time", table_name="normalized_events")
    op.drop_index(op.f("ix_normalized_events_source_ip"), table_name="normalized_events")
    op.drop_index(op.f("ix_normalized_events_severity"), table_name="normalized_events")
    op.drop_index(op.f("ix_normalized_events_raw_event_id"), table_name="normalized_events")
    op.drop_index(op.f("ix_normalized_events_log_source"), table_name="normalized_events")
    op.drop_index("ix_normalized_events_host_time", table_name="normalized_events")
    op.drop_index(op.f("ix_normalized_events_host"), table_name="normalized_events")
    op.drop_index(op.f("ix_normalized_events_event_type"), table_name="normalized_events")
    op.drop_index(op.f("ix_normalized_events_event_timestamp"), table_name="normalized_events")
    op.drop_index(op.f("ix_normalized_events_destination_ip"), table_name="normalized_events")
    op.drop_table("normalized_events")
    op.drop_index(op.f("ix_user_accounts_username"), table_name="user_accounts")
    op.drop_index(op.f("ix_user_accounts_role"), table_name="user_accounts")
    op.drop_table("user_accounts")
    op.drop_index(op.f("ix_raw_events_received_at"), table_name="raw_events")
    op.drop_index(op.f("ix_raw_events_log_source"), table_name="raw_events")
    op.drop_table("raw_events")
    op.drop_index(op.f("ix_model_runs_status"), table_name="model_runs")
    op.drop_index(op.f("ix_model_runs_model_name"), table_name="model_runs")
    op.drop_table("model_runs")
    op.drop_index(
        op.f("ix_indicators_of_compromise_indicator_type"), table_name="indicators_of_compromise"
    )
    op.drop_table("indicators_of_compromise")
    op.drop_index(op.f("ix_incidents_status"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_severity"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_audit_logs_resource_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_username"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_attack_graph_nodes_entity_type"), table_name="attack_graph_nodes")
    op.drop_table("attack_graph_nodes")
    op.drop_index(op.f("ix_asset_hosts_hostname"), table_name="asset_hosts")
    op.drop_table("asset_hosts")
    # ### end Alembic commands ###
